# Generated by Django 5.1.7 on 2025-05-04 21:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="core/images/hero-bg.jpg",
                upload_to=core.models.user_directory_path,
            ),
        ),
    ]
